spring.application.name=TrabalhoBack
spring.datasource.url=jdbc:postgresql://localhost:3001/biblioteca
spring.datasource.username=postgres
spring.datasource.password=0212

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true